### ISSUE TITLE
Request: Container for gliderlabs/logspout?

### ISSUE THREAD

**Issue by OneCricketeer** [armhf-docker-library/logstash#2]
I use [logspout](http://gliderlabs.com/blog/2015/03/31/new-logspout-extensible-docker-logging/) to sending container logs to logstash. 

I made a simple [armhf fork](https://github.com/cricket007/logspout/tree/armhf), for it, but I see you're using drone to do some builds, so I was hoping you could just use my repo as an example. 

Pushed to [Docker Hub](https://hub.docker.com/r/cricketeerone/armhf-logspout/) also using Raspberry Pi 3 as build device.

**Comment by djmaze** [comment]
Oh well, it's been a long time. Did not get any notifications for this, very sorry. 

I will hopefully soon try to get Drone 0.5 working on arm. Afterwards it would be nice to take on images like this.

**Comment by OneCricketeer** [comment]
@djmaze No worries. Is there a place one can push into the `armhf-docker-library` or make formal submissions? 

I'm fine keeping my own version, but it would make it easier to search over Docker Hub for armhf images when there is some "master" repository.

**Comment by djmaze** [comment]
@cricket007 As this library is a private spare-time effort, there is no official way to make submissions. 

That said, I just created a [gitter channel](https://gitter.im/armhf-docker-library) for people to discuss and make suggestions. If you have an image you want included, just ask and we can fork your existing repository or create a new one.

**Comment by OneCricketeer** [comment]
👍
